### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by tdutrion** [darkmira/group-website#1]
Add favicon to every page of the website.

```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

[favicon_package_v0.16.zip](https://github.com/darkmira/group-website/files/3669555/favicon_package_v0.16.zip)

**Comment by denisolvr** [comment]
Hi @tdutrion, I added a pull request adding favicon for your project. Can you have a look and give me a feedback?

**Comment by AnonProductions** [comment]
Hi @tdutrion could you please check the PR on adding favicon? [Add favicon](https://github.com/darkmira/group-website/pull/4)

**Comment by tdutrion** [comment]
Hi @denisolvr and @AnonProductions!

Thank you both for your work. I merged @denisolvr's PR as I had to make a choice and he did contribute first, but thanks again to both of you.

**Comment by AnonProductions** [comment]
No issue man...it was great working on this :)
